# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=500, verbose_name='Comp\xe9tences cl\xe9es')),
                ('localisation', models.CharField(max_length=500, verbose_name='Localisation recherch\xe9e')),
                ('experience', models.IntegerField(verbose_name="Ann\xe9es d'exp\xe9rience")),
                ('email_adress', models.EmailField(max_length=254, verbose_name='Votre adresse e-mail')),
                ('bu', models.CharField(choices=[('DS', 'Data Science'), ('EMA', 'Enterprise Marketing Automation'), ('CRM', 'Customer Relationship Management'), ('SUP', 'Support'), ('DF', 'Digital Factory'), ('BC', 'Business Consulting')], max_length=3)),
            ],
            options={
                'db_table': 'Bu',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.FileField(upload_to='photos/')),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
    ]
